-- =============================================================================
--  SEED DATA - BASE REFERENCE DATA
--  File    : database/02-seed/seed-data.sql
--  Target  : PostgreSQL 13+
--
--  WHAT THIS FILE CREATES:
--    1. categories  - 8 product groups
--    2. stores      - 10 shops (store_id 1-10, matches Kaggle store column)
--    3. products    - 50 products (product_id 1-50, matches Kaggle item column)
--    4. users       - 3 accounts (owner / manager / staff)
--
--  IMPORTANT - WHY IDs ARE FIXED:
--    The Kaggle dataset (Walmart Store Sales) uses store 1-10 and item 1-50.
--    We insert rows with EXPLICIT ids so that order_items.product_id and
--    orders.store_id can be imported directly without a mapping table.
--    This is the reason we do NOT use GENERATED BY DEFAULT AS IDENTITY here.
--
--  NOT INCLUDED IN THIS FILE:
--    - orders / order_items  -> imported from Kaggle (see scripts/import_kaggle.py)
--    - inventory, inventory_transactions, forecasts, alerts
--      -> generated in a later step, see GHI-CHU-TIEN-DO.md section 8
--
--  USAGE:
--    psql -U postgres -d spoilage_predictor -v ON_ERROR_STOP=1 -f database/02-seed/seed-data.sql
--
--  RE-RUNNING:
--    The TRUNCATE at the top wipes child tables too (CASCADE), so this file
--    can be run repeatedly without duplicate key errors.
-- =============================================================================

BEGIN;

SET client_min_messages = WARNING;

-- Clear previous run (CASCADE reaches child tables)
TRUNCATE alerts, forecasts, order_items, orders, inventory_transactions,
         inventory, products, categories, users, stores
    RESTART IDENTITY CASCADE;


-- =============================================================================
--  1. CATEGORIES - 8 product groups
-- -----------------------------------------------------------------------------
--  parent_category_id is set in a second pass so groups can be nested.
--  Hierarchy:  1 Food
--                 2 Fresh Food
--                 3 Beverages
--                 4 Snacks
--                 5 Household
-- =============================================================================
INSERT INTO categories (category_id, category_name, description, parent_category_id) VALUES
    (1, 'Food',              'Tat ca nhom thuc pham',                      NULL),
    (2, 'Fresh Food',        'Rau cu, trai cay, thit, trung, thuy san',    1),
    (3, 'Beverages',         'Nuoc giai khat, sua, tra, ruou',              1),
    (4, 'Snacks',            'Banh, keo, banh quy, hat',                    1),
    (5, 'Household',         'Ve sinh, tam hop, giay nha',                 NULL),
    (6, 'Personal Care',     'Cham soc ca nhan, my pham',                   NULL),
    (7, 'Baby Care',         'Dung cho tre em',                             NULL),
    (8, 'Dairy',             'Sua, pho mat, banh',                          NULL);


-- =============================================================================
--  2. STORES - 10 shops (store_id 1-10, matches Kaggle store column)
-- -----------------------------------------------------------------------------
--  store_type mixes convenience stores, restaurants and a warehouse to
--  exercise the F&B part of the project brief.
-- =============================================================================
INSERT INTO stores (store_id, store_code, store_name, address, phone, store_type, opening_date, is_active) VALUES
    ( 1, 'CH01', 'Cua hang tien loi Q.3',    '123 Nguyen Hue, Q.3, TP.HCM',            '0901000001', 'convenience_store', '2015-03-01', TRUE),
    ( 2, 'CH02', 'Cua hang tien loi Binh Thanh','456 Dien Bien Phu, Binh Thanh, TP.HCM',  '0901000002', 'convenience_store', '2015-07-15', TRUE),
    ( 3, 'CH03', 'Cua hang tien loi Thu Duc','789 Vo Van Kiet, Thu Duc, TP.HCM',        '0901000003', 'convenience_store', '2016-01-10', TRUE),
    ( 4, 'CH04', 'Cua hang tien loi Tan Binh','321 Au Co, Tan Binh, TP.HCM',            '0901000004', 'convenience_store', '2016-05-20', TRUE),
    ( 5, 'CH05', 'Cua hang tien loi Hai Ba Trung','654 Cach Mang Thang 8, Q.10, TP.HCM',  '0901000005', 'convenience_store', '2016-09-01', TRUE),
    ( 6, 'NH01', 'Nha hang Mon An 1',       '12 Le Loi, Q.1, TP.HCM',                  '0901000006', 'restaurant',        '2016-11-05', TRUE),
    ( 7, 'NH02', 'Nha hang Mon An 2',       '34 Hai Ba Trung, Q.5, TP.HCM',            '0901000007', 'restaurant',        '2017-02-14', TRUE),
    ( 8, 'NH03', 'Nha hang Mon An 3',       '56 Nguyen Trai, Q.5, TP.HCM',             '0901000008', 'restaurant',        '2017-06-30', TRUE),
    ( 9, 'KHO1', 'Kho phan phoi Bai Bang','88 Quang Trung, Binh Thanh, TP.HCM',       '0901000009', 'warehouse',         '2015-01-01', TRUE),
    (10, 'CH06', 'Cua hang tien loi Da Nang','22 Vo Van Kiet, Hai Chau, Da Nang',       '0901000010', 'convenience_store', '2017-08-08', TRUE);


-- =============================================================================
--  3. PRODUCTS - 50 products (product_id 1-50, matches Kaggle item column)
-- -----------------------------------------------------------------------------
--  Prices are REALISTIC Vietnamese market prices, written as MOCK DATA.
--  They are NOT measured survey figures - say so explicitly in the report.
--
--  ID 1-50 matches the Kaggle "item" column so the import needs no mapping.
--  Naming is generic by category because Kaggle does not publish item names;
--  real item names would be assigned once the real POS data is available.
-- =============================================================================

-- Group 2: Fresh Food (items 1-10)
INSERT INTO products
    (product_id, product_code, product_name, category_id, unit, unit_cost, selling_price, shelf_life_days, min_stock, max_stock, is_perishable, reorder_point, supplier) VALUES
    ( 1, 'SP0001', 'Rau muong toi',          2, 'kg',      18000,  28000,  3,  10,  60, TRUE,  20, 'Cong ty Rau Xanh A'),
    ( 2, 'SP0002', 'Rau cai thuong',         2, 'kg',      15000,  25000,  5,  15,  80, TRUE,  25, 'Cong ty Rau Xanh A'),
    ( 3, 'SP0003', 'Khoai lang',             2, 'kg',      22000,  35000, 30,  20, 100, TRUE,  30, 'Cong ty Rau Xanh A'),
    ( 4, 'SP0004', 'Cam suoi',               2, 'kg',      45000,  68000,  7,   8,  40, TRUE,  15, 'Trai cay Mien Nam'),
    ( 5, 'SP0005', 'Buoi Long An',           2, 'kg',      38000,  58000, 10,   8,  40, TRUE,  15, 'Trai cay Mien Nam'),
    ( 6, 'SP0006', 'Chuoi hoc',              2, 'kg',      20000,  32000,  4,  10,  50, TRUE,  20, 'Trai cay Mien Nam'),
    ( 7, 'SP0007', 'Thit ga ta moi',         2, 'kg',      52000,  78000,  2,  15,  70, TRUE,  25, 'Cong ty Thuc Phan'),
    ( 8, 'SP0008', 'Thit bo',                2, 'kg',      98000, 145000,  3,  10,  50, TRUE,  20, 'Cong ty Thuc Phan'),
    ( 9, 'SP0009', 'Ca tai tuoi',            2, 'kg',      45000,  69000,  2,  10,  45, TRUE,  20, 'Thuy Hai San Dong'),
    (10, 'SP0010', 'Trung ga',               2, 'kg',      32000,  45000, 20,  12,  60, TRUE,  20, 'Trang Trai Mien Nam');

-- Group 3: Beverages (items 11-25)
INSERT INTO products
    (product_id, product_code, product_name, category_id, unit, unit_cost, selling_price, shelf_life_days, min_stock, max_stock, is_perishable, reorder_point, supplier) VALUES
    (11, 'SP0011', 'Nuoc loc 500ml',          3, 'chai',   4500,   8000, 180,  50, 300, FALSE, 100, 'Cong ty Nuoc Lich'),
    (12, 'SP0012', 'Nuoc khoang 500ml',      3, 'chai',   5000,   9000, 365,  40, 250, FALSE,  80, 'Cong ty Nuoc Lich'),
    (13, 'SP0013', 'Nuoc sui 330ml',          3, 'lon',    7000,  12000, 180,  40, 240, FALSE,  80, 'Cong ty Giai Khat'),
    (14, 'SP0014', 'Tra xanh chai',           3, 'chai',   6000,  10000, 270,  30, 200, FALSE,  60, 'Cong ty Tra'),
    (15, 'SP0015', 'Ca phe sua dinh huong',   3, 'hop',   18000,  26000, 365,  25, 150, FALSE,  50, 'Cong ty Ca Phe'),
    (16, 'SP0016', 'Ca phe den',              3, 'hop',   20000,  29000, 365,  25, 150, FALSE,  50, 'Cong ty Ca Phe'),
    (17, 'SP0017', 'Sua tuoi tu 1 lit',       8, 'hop',   16000,  22000,  10,  30, 180, TRUE,   50, 'Cong ty Sua'),
    (18, 'SP0018', 'Sua chua 500g',          8, 'hop',   14000,  19000,  21,  25, 150, TRUE,   40, 'Cong ty Sua'),
    (19, 'SP0019', 'Pho mai lat',            8, 'kg',    45000,  65000,  30,  10,  50, TRUE,   20, 'Cong ty Sua'),
    (20, 'SP0020', 'Ban cuon mat',            8, 'kg',    12000,  18000,  14,  20, 100, TRUE,   35, 'Tiem Ba Gia'),
    (21, 'SP0021', 'Nuoc dua 250ml',          3, 'chai',   5000,   8500, 120,  30, 180, TRUE,   50, 'Cong ty Giai Khat'),
    (22, 'SP0022', 'Tra dau khong',           3, 'hop',    8000,  13000, 180,  20, 120, FALSE,   40, 'Cong ty Tra'),
    (23, 'SP0023', 'Nuoc tang rut',           3, 'chai',   6000,   9500, 270,  30, 200, FALSE,   60, 'Cong ty Giai Khat'),
    (24, 'SP0024', 'Sirap dau',               3, 'chai',   9000,  15000, 365,  12,  80, FALSE,   25, 'Cong ty Syrup'),
    (25, 'SP0025', 'Ruou dua co',            3, 'chai',  12000,  18000, 730,  10,  60, FALSE,   20, 'Cong ty Ruou');

-- Group 4: Snacks (items 26-35)
INSERT INTO products
    (product_id, product_code, product_name, category_id, unit, unit_cost, selling_price, shelf_life_days, min_stock, max_stock, is_perishable, reorder_point, supplier) VALUES
    (26, 'SP0026', 'Ban quy',                 4, 'goi',   15000,  22000,  90,  20, 120, TRUE,   40, 'Cong ty Banh'),
    (27, 'SP0027', 'Banh snack',              4, 'goi',    8000,  13000,  60,  25, 150, TRUE,   50, 'Cong ty Banh'),
    (28, 'SP0028', 'Keo mut',                 4, 'goi',    6000,  10000, 365,  20, 120, FALSE,  40, 'Cong ty Keo'),
    (29, 'SP0029', 'So Co-la',                4, 'chai',  18000,  27000, 365,  12,  72, FALSE,  24, 'Cong ty Do Uong'),
    (30, 'SP0030', 'Banh tuoi',               4, 'goi',    5000,   9000,  2,  30, 150, TRUE,   60, 'Tiem Ba Gia'),
    (31, 'SP0031', 'Banh trung cuon',         4, 'goi',    4000,   7000,  2,  30, 150, TRUE,   60, 'Tiem Ba Gia'),
    (32, 'SP0032', 'Hat dieu',                4, 'goi',   20000,  32000, 120,  15,  90, TRUE,   30, 'Cong ty Hat'),
    (33, 'SP0033', 'Hat hat',                 4, 'goi',    7000,  12000,  90,  15,  90, TRUE,   30, 'Cong ty Hat'),
    (34, 'SP0034', 'Pho mai vi t',            4, 'hop',   25000,  38000, 180,  10,  60, TRUE,   20, 'Cong ty Pho Mai'),
    (35, 'SP0035', 'Tram tam cau',            4, 'hop',   30000,  45000, 240,   8,  48, TRUE,   16, 'Cong ty Tam Cau');

-- Group 5: Household (items 36-42)
INSERT INTO products
    (product_id, product_code, product_name, category_id, unit, unit_cost, selling_price, shelf_life_days, min_stock, max_stock, is_perishable, reorder_point, supplier) VALUES
    (36, 'SP0036', 'Giat xa tang',           5, 'chai',  28000,  42000, 730,  10,  60, FALSE,  20, 'Cong ty Gia Dung'),
    (37, 'SP0037', 'Dau goi',                 5, 'chai',  55000,  80000, 730,   8,  48, FALSE,  16, 'Cong ty My Pham'),
    (38, 'SP0038', 'Sua tam the',             5, 'chai',  38000,  58000, 730,  10,  60, FALSE,  20, 'Cong ty Cham Soc'),
    (39, 'SP0039', 'Giay an toi',             5, 'thung', 22000,  34000, 365,  15,  90, FALSE,  30, 'Cong ty Ve Sinh'),
    (40, 'SP0040', 'Bong bien sang',          5, 'chai',   8000,  14000, 730,  12,  72, FALSE,  24, 'Cong ty Ve Sinh'),
    (41, 'SP0041', 'Dieu hoa khong moi',      5, 'chai',  18000,  29000, 365,  10,  60, TRUE,   20, 'Cong ty Lam Sach'),
    (42, 'SP0042', 'Nuoc rua bat',            5, 'chai',  15000,  24000, 730,   8,  48, FALSE,  16, 'Cong ty Lam Sach');

-- Group 6/7/8: Personal care, baby care, other (items 43-50)
INSERT INTO products
    (product_id, product_code, product_name, category_id, unit, unit_cost, selling_price, shelf_life_days, min_stock, max_stock, is_perishable, reorder_point, supplier) VALUES
    (43, 'SP0043', 'Kem chong nang',          6, 'chai',  95000, 135000, 365,   6,  36, FALSE,  12, 'Cong ty My Pham'),
    (44, 'SP0044', 'Sua tam the tre em',      7, 'chai',  62000,  89000, 730,   6,  36, FALSE,  12, 'Cong ty Cham Soc Tre Em'),
    (45, 'SP0045', 'Khan uot tre em',         7, 'chai',  35000,  55000, 730,   8,  48, FALSE,  16, 'Cong ty Cham Soc Tre Em'),
    (46, 'SP0046', 'Thuc pham an dam',        7, 'hop',  120000, 175000, 540,   6,  36, FALSE,  12, 'Cong ty Thuc Pham Tre Em'),
    (47, 'SP0047', 'Bot loc nuoc',            6, 'bo',    85000, 120000, 730,   5,  30, FALSE,  10, 'Cong ty Gia Dung'),
    (48, 'SP0048', 'Kem danh rang',           6, 'tube',  25000,  38000, 730,  10,  60, FALSE,  20, 'Cong ty Cham Soc'),
    (49, 'SP0049', 'Xa phong',                5, 'goi',   12000,  20000, 730,  15,  90, FALSE,  30, 'Cong ty Ve Sinh'),
    (50, 'SP0050', 'Que doi',                 5, 'hop',     500,   1500, 365,  20, 120, FALSE,  40, 'Cong ty Ve Sinh');


-- =============================================================================
--  4. USERS - 3 accounts
-- -----------------------------------------------------------------------------
--  password_hash holds a placeholder, NOT a real hash. Generate with:
--      python -c "import bcrypt; print(bcrypt.hashpw(b'123', bcrypt.gensalt()).decode())"
--  The login feature is not built yet; authentication is planned for a later
--  phase. Do not treat these rows as working credentials.
-- =============================================================================
INSERT INTO users (user_id, username, email, password_hash, full_name, role, store_id, is_active) VALUES
    (1, 'owner',    'owner@shop.local',    'PLACEHOLDER_NOT_A_REAL_HASH_1', 'Chu chuoi',      'owner',   NULL, TRUE),
    (2, 'manager',  'manager@shop.local',  'PLACEHOLDER_NOT_A_REAL_HASH_2', 'Quan ly tong',   'manager',  NULL, TRUE),
    (3, 'staff',    'staff@shop.local',    'PLACEHOLDER_NOT_A_REAL_HASH_3', 'Nhan vien kho',  'staff',     1, TRUE);

COMMENT ON TABLE products IS
    'Mock prices - realistic Vietnamese market values, NOT measured survey data. Say so explicitly in the report.';

-- Commit is REQUIRED here. Without it psql rolls back on exit and nothing
-- is saved, even though the verification queries below still see the rows.
COMMIT;


-- =============================================================================
--  VERIFICATION
-- =============================================================================
\echo '--- Row counts (expected: categories 8, stores 10, products 50, users 3) ---'
SELECT 'categories' AS bang, COUNT(*) AS so_dong FROM categories
UNION ALL SELECT 'stores',     COUNT(*) FROM stores
UNION ALL SELECT 'products',   COUNT(*) FROM products
UNION ALL SELECT 'users',      COUNT(*) FROM users
ORDER BY bang;

\echo '--- ID range must match Kaggle: stores 1-10, products 1-50 ---'
SELECT
    MIN(store_id)   AS store_min,   MAX(store_id)   AS store_max,
    MIN(product_id) AS product_min, MAX(product_id) AS product_max
FROM stores, products;

\echo '--- FK integrity: every product must map to a category ---'
SELECT COUNT(*) AS san_pham_orphan
FROM products p
LEFT JOIN categories c ON c.category_id = p.category_id
WHERE c.category_id IS NULL;

\echo '--- Seed done. Next: python scripts/import_kaggle.py ---'


-- =============================================================================
--  NOTES
-- =============================================================================
--
--  1. EXPLICIT IDS:
--     Rows are inserted with explicit ids (not auto-generated) because the
--     Kaggle dataset uses item 1-50 and store 1-10. This removes the need for
--     a mapping table during import. RESTART IDENTITY in the TRUNCATE keeps the
--     sequences aligned so later inserts (orders, inventory) start from 1.
--
--  2. MOCK DATA:
--     Product names are generic and prices are realistic but invented. The
--     Kaggle dataset contains no product names or prices, so real names would
--     have to come from the retail partner's POS system. State this clearly
--     in the report - do not present these as surveyed figures.
--
--  3. SHELF LIFE:
--     Fresh items are 2-10 days (short), packaged food 60-180 days, and
--     non-food household items 365-730 days. The project brief targets items
--     with a shelf life under 90 days, so 27 of the 50 products are
--     is_perishable = TRUE.
--
--  4. WHY orders/order_items ARE NOT SEEDED HERE:
--     Sales history comes from the Kaggle import (scripts/import_kaggle.py).
--     Seeding fake orders here would create two sources of truth for the same
--     "sales" concept and risk divergence between them.
-- =============================================================================
