-- =============================================================================
--  SEED DATA - INVENTORY AND STOCK TRANSACTIONS
--  File    : database/02-seed/seed-inventory.sql
--  Run AFTER: database/02-seed/seed-data.sql  (needs products / stores / users)
--
--  WHAT THIS FILE CREATES:
--    1. inventory              - approx. 1,500 batches (50 products x 10 stores
--                                 x 3 batches each)
--    2. inventory_transactions - approx. 1,800 movements
--    3. alerts                 - generated by fn_generate_inventory_alerts()
--
--  COLUMN NAME NOTE:
--    The task brief called them "batch_number" and "import_date".
--    The real columns in schema are batch_code and received_date.
--
--  DETERMINISTIC DATA:
--    No random() is used. Every value derives from (product_id, store_id,
--    batch_no) through fixed arithmetic, so re-running this file always
--    produces identical data and the checks below stay meaningful.
--
--  SCENARIOS DELIBERATELY CREATED:
--    - expired batches     : ~5%  (expiry_date < today)
--    - expiring soon       : ~15% (expiry within 7 days)
--    - thin stock          : ~8%  of product/shop pairs -> low stock alerts
--    - over stock          : ~8%  of product/shop pairs -> over stock alerts
--    The last two are needed because otherwise every shop holds far more
--    stock than min_stock/max_stock and no alert would ever fire.
--
--  USAGE:
--    psql -U postgres -d spoilage_predictor -v ON_ERROR_STOP=1 \
--         -f database/02-seed/seed-inventory.sql
-- =============================================================================

BEGIN;

SET client_min_messages = WARNING;

-- Clear previous run
TRUNCATE alerts, inventory_transactions, inventory RESTART IDENTITY CASCADE;


-- =============================================================================
--  1. INVENTORY - approx. 1,500 batches
-- -----------------------------------------------------------------------------
--  Quantity scenarios are decided per (product_id, store_id) PAIR so that the
--  SUM across a pair falls below min_stock or above max_stock. Deciding per
--  batch would never trigger those alerts, because 3 normal batches always
--  add up to more than min_stock.
-- =============================================================================

INSERT INTO inventory (store_id, product_id, expiry_date, quantity, received_date, batch_code)
SELECT
    c.store_id,
    c.product_id,
    CURRENT_DATE + cap.expiry_offset,
    q.quantity,
    (CURRENT_DATE + cap.expiry_offset) - pr.shelf_life_days,
    'BATCH-' || TO_CHAR(CURRENT_DATE, 'YYYY') || '-' || LPAD(c.seq::TEXT, 6, '0')
FROM (
    SELECT
        g.product_id,
        g.shelf_life_days,
        g.min_stock,
        g.max_stock,
        s.store_id,
        b.batch_no,
        COUNT(*) OVER (PARTITION BY g.product_id, s.store_id) AS batch_count,
        ROW_NUMBER() OVER (ORDER BY g.product_id, s.store_id, b.batch_no) AS seq,
        -- Deterministic pseudo-random bucket in 0..99.
        -- md5 is used instead of simple arithmetic because
        --   (product_id * 17 + store_id * 37) % 100
        -- is NOT uniformly distributed: it produced 78% over-stock pairs
        -- instead of the intended 16%.
        (get_byte(decode(md5('b' || g.product_id || '-' || s.store_id
                             || '-' || b.batch_no), 'hex'), 0) % 100)
            AS batch_bucket,
        (get_byte(decode(md5('p' || g.product_id || '-' || s.store_id),
                         'hex'), 0) % 100)
            AS pair_bucket
    FROM products g
    CROSS JOIN stores s
    -- Short shelf life items cannot hold several batches at once.
    -- A shop with lettuce that keeps 2 days realistically has ONE lettuce
    -- batch, not three.
    CROSS JOIN LATERAL generate_series(
        1, CASE WHEN g.shelf_life_days <= 3 THEN 1
                WHEN g.shelf_life_days <= 10 THEN 2
                ELSE 3 END
    ) AS b(batch_no)
) c
JOIN products pr ON pr.product_id = c.product_id
CROSS JOIN LATERAL (
    -- Expiry offset derived from batch_no, so every batch of the same
    -- product/shop gets a DIFFERENT expiry date. That matters because
    -- UNIQUE (store_id, product_id, expiry_date) would reject duplicates.
    --
    --   expired        -> -1, -2, -3        (distinct)
    --   expiring soon  ->  1,  2,  3        (distinct)
    --   normal         ->  shelf-1, shelf-2, shelf-3
    SELECT CASE
        WHEN c.batch_bucket < 5 THEN -c.batch_no
        WHEN c.batch_bucket < 20 THEN c.batch_no
        ELSE GREATEST(1, c.shelf_life_days - c.batch_no)
    END AS expiry_offset
) cap
CROSS JOIN LATERAL (
    -- Quantity per batch. Three cases:
    --
    --   thin   : 1 per batch -> total 1-3, always below min_stock
    --   over   : 350 per batch -> total >= 350, always above max_stock
    --   normal : sized from max_stock / min_stock so that the SUM stays in a
    --             healthy band.
    --
    -- The normal case MUST be derived from the thresholds. A flat random
    -- range such as 10-200 per batch gives 30-600 per product/shop, which
    -- already exceeds most max_stock values (30-300) and makes over-stock
    -- alerts fire almost everywhere, hiding the deliberate test case.
    SELECT CASE
        WHEN c.pair_bucket < 8  THEN 1
        WHEN c.pair_bucket < 16 THEN 350
        ELSE GREATEST(
            1,
            GREATEST(c.max_stock * 0.45, c.min_stock * 1.5) / c.batch_count
        )
    END AS quantity
) q;


-- =============================================================================
--  2. INVENTORY TRANSACTIONS - approx. 1,800 movements
-- -----------------------------------------------------------------------------
--  Three groups:
--    a) import     - one per inventory batch, dated at received_date
--    b) export     - linked to real orders imported from Kaggle
--    c) disposal   - for expired batches (spoilage write-off)
--
--  IMPORTANT - SCOPE OF THIS DATA:
--  These movements are SYNTHETIC demo data. They are NOT derived from the
--  Kaggle sales figures. The real sales history lives in orders + order_items.
--  The forecasting model is fed from orders/order_items, not from this table.
-- =============================================================================

-- a) Import movement for every batch
INSERT INTO inventory_transactions
    (store_id, product_id, expiry_date, transaction_type, quantity,
     unit_cost, reference_type, reference_id, transaction_date, user_id, note)
SELECT
    i.store_id,
    i.product_id,
    i.expiry_date,
    'import',
    i.quantity,
    pr.unit_cost,
    'manual',
    i.inventory_id,
    i.received_date::TIMESTAMPTZ,
    1,
    'Nhap len tu nha cung cap'
FROM inventory i
JOIN products pr ON pr.product_id = i.product_id;


-- b) Export movements linked to real Kaggle orders (first 200 orders)
--    expiry_date is left NULL on purpose: a sales order does not name a batch.
--    NULL values do not collide in the unique constraint, which is correct
--    because one order can sell several batches of the same product.
INSERT INTO inventory_transactions
    (store_id, product_id, expiry_date, transaction_type, quantity,
     unit_cost, reference_type, reference_id, transaction_date, user_id, note)
SELECT
    o.store_id,
    oi.product_id,
    NULL,
    'export',
    oi.quantity,
    oi.unit_price,
    'order',
    o.order_id,
    o.order_date,
    3,
    'Ban hang tu don ' || o.order_code
FROM orders o
JOIN order_items oi ON oi.order_id = o.order_id
WHERE o.order_id <= 200;


-- c) Disposal of expired batches (this is the spoilage the project fights)
INSERT INTO inventory_transactions
    (store_id, product_id, expiry_date, transaction_type, quantity,
     unit_cost, reference_type, reference_id, transaction_date, user_id, note)
SELECT
    i.store_id,
    i.product_id,
    i.expiry_date,
    'disposal',
    i.quantity,
    pr.unit_cost,
    'manual',
    -- Negative id keeps disposal in a different key namespace from the import
    -- movement above. Both use reference_type = 'manual' and the same
    -- inventory_id, so without the sign change they would collide on
    -- UNIQUE (reference_type, reference_id, product_id, expiry_date).
    -i.inventory_id,
    CURRENT_DATE,
    2,
    'Tieu huu vi het han su dung'
FROM inventory i
JOIN products pr ON pr.product_id = i.product_id
WHERE i.expiry_date < CURRENT_DATE
  AND i.quantity > 0;


-- =============================================================================
--  3. GENERATE ALERTS
-- -----------------------------------------------------------------------------
--  Calls the phase 1 alert function with a 7 day warning window.
--  Function is idempotent: it skips products that already have an unresolved
--  alert of the same type.
-- =============================================================================

-- Print only the TOTAL. The function returns one row per alert, and dumping
-- ~400 rows into the console hides everything else.
SELECT COUNT(*) AS alerts_created FROM fn_generate_inventory_alerts(7);


COMMIT;


-- =============================================================================
--  VERIFICATION
-- =============================================================================
\echo '--- Row counts ---'
SELECT 'inventory'              AS bang, COUNT(*) AS so_dong FROM inventory
UNION ALL SELECT 'inventory_transactions', COUNT(*) FROM inventory_transactions
UNION ALL SELECT 'alerts',                  COUNT(*) FROM alerts
ORDER BY bang;

\echo '--- Batch expiry distribution (expected: approx 5% expired, 15% soon) ---'
SELECT
    CASE
        WHEN expiry_date <  CURRENT_DATE THEN '1. da het han'
        WHEN expiry_date <= CURRENT_DATE + 7 THEN '2. sap het han'
        ELSE '3. con lai'
    END AS nhom,
    COUNT(*) AS so_lot,
    ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (), 1) AS ty_le_le
FROM inventory
GROUP BY 1
ORDER BY 1;

\echo '--- Alerts by type (expected: expired / expiring_soon / low_stock / over_stock) ---'
SELECT alert_type, severity, COUNT(*) AS so_canh_bao
FROM alerts
GROUP BY alert_type, severity
ORDER BY alert_type, severity;

\echo '--- Alerts title must hold i18n KEYS, not display text ---'
SELECT DISTINCT title FROM alerts ORDER BY title;

\echo '--- Expired batches (LIMIT 5) ---'
SELECT store_id, product_id, batch_code, quantity, expiry_date, received_date
FROM inventory
WHERE expiry_date < CURRENT_DATE
ORDER BY expiry_date
LIMIT 5;

\echo '--- v_expiring_inventory (LIMIT 5) ---'
SELECT product_name, batch_code, quantity, expiry_date, days_to_expiry, alert_severity
FROM v_expiring_inventory
ORDER BY days_to_expiry
LIMIT 5;

\echo '--- v_low_stock (LIMIT 5) ---'
SELECT product_name, total_quantity, min_stock, shortage
FROM v_low_stock
ORDER BY shortage DESC
LIMIT 5;

\echo '--- Sanity: no orphan rows, no negative stock ---'
SELECT
    (SELECT COUNT(*) FROM inventory WHERE quantity < 0) AS so_ton_am,
    (SELECT COUNT(*) FROM inventory i
       LEFT JOIN products p ON p.product_id = i.product_id
      WHERE p.product_id IS NULL) AS san_pham_orphan,
    (SELECT COUNT(*) FROM inventory_transactions WHERE quantity <= 0) AS gd_khong_hop_le;


-- =============================================================================
--  NOTES
-- =============================================================================
--
--  1. WHY SCENARIOS ARE DECIDED PER PAIR, NOT PER BATCH:
--     Alert rules compare the SUM of stock for a product at a shop against
--     min_stock / max_stock. With 3 normal batches per pair the sum is always
--     far above both thresholds, so no alert would ever fire. Assigning the
--     "thin" and "over" scenarios at pair level makes the rules testable.
--
--  2. WHY expiry_date IS CAPPED BY shelf_life_days:
--     An item with shelf_life_days = 2 cannot have an expiry 40 days out.
--     LEAST(raw_offset, shelf_life_days) keeps the data physically possible.
--     Side effect: short shelf life items cluster near their expiry date,
--     which is realistic and will show up in v_expiring_inventory.
--
--  3. WHY export TRANSACTIONS LEAVE expiry_date NULL:
--     UNIQUE (reference_type, reference_id, product_id, expiry_date) treats
--     NULLs as distinct, so one order selling several batches of the same
--     product does not violate the constraint. Sales orders genuinely do not
--     specify which batch was picked.
--
--  4. THIS TABLE IS NOT THE FORECASTING INPUT:
--     These movements are synthetic. Real sales history lives in orders and
--     order_items (imported from Kaggle). Feed the forecasting model from
--     v_daily_sales, which reads from orders/order_items.
--
--  5. i18n:
--     alerts.title holds KEYS such as 'alert.title.EXPIRED'. The backend
--     resolves them through backend/app/i18n/vi.json. Do not hardcode
--     Vietnamese text here - this file must stay pure ASCII to run on Windows.
-- =============================================================================
